name: Maven Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Rename Extent Report with Timestamp
        if: always()
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          if [ -f "extent-reports/extent-report.html" ]; then
            mv extent-reports/extent-report.html extent-reports/extent-report-${TIMESTAMP}.html
          fi

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-${{ github.run_number }}
          path: extent-reports/
          retention-days: 30

      - name: Upload TestNG Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-results
          path: target/surefire-reports/
          retention-days: 30
